import "./globals.css";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import QueryProvider from "@/providers/QueryProvider";
import ResponsiveLayout from "@/components/ResponsiveLayout";
import LeftBar from "@/components/LeftBar";
import RightBar from "@/components/RightBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <QueryProvider>
        <html lang="en">
          <body>
            {/* 1. Wrap the main content in your Responsive structure */}
            <ResponsiveLayout leftBar={<LeftBar />} rightBar={<RightBar />}>
              {children}
            </ResponsiveLayout>

            {modal}
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
